/*PUSHKARA RAVINDRA 2011A7PS150P
 *VIRAJ PRABHU	    2011A7PS044P
 * BATCH-1*/
/*DRIVER FUNCTION*/
#include<stdio.h>
#include<string.h>
#include<stdlib.h>
#include "lexerDef.h"
#include "lexer.h"
#include "parser.h"
#include "symbolTable.h"
#include "astDef.h"
#include "codegen.h"

extern int STerror;
extern symbolTable* createSymbolTable(ast_node* a, symbolTable* ST);
extern void printSymbolTable(ast_node* a, symbolTable* ST);
extern int initTypeChecker(ast_node* a, symbolTable* ST);
extern parseTree initParser(char* tsf);
extern void handleCase4(symbolTable* ST, int choice);
void printAST(ast_node* a);
ast_node* a;

parseTree R;
//char tsf[50] = "testcase.txt";
char tsf[50];
char psrf[50] = "output.txt";
int main(int argc, char *argv[])
{	  
	symbolTable* ST;
	strcpy(tsf, argv[1]);
	strcpy(psrf,argv[2]);
	printf("LEVEL 2: Symbol table,  AST, Type Checker and Semantic Rules modules work.\n");
	a = NULL;
	ST = NULL;
	int choice;
	  
	  printf("Choose one from the following options:\n");
	  printf("\t1:For  printing the token list (on the console) generated by the lexer\n");
	  printf("\t2:For parsing to verify the syntactic correctness of the input source code and to produce parse tree \n"); 
	  printf("\t3:For printing the Abstract Syntax Tree in depth first order\n");
	  printf("\t4:For printing the Symbol Table\n");
	  printf("\t5:For performing type and semantic checks\n");
	  printf("\t6:For generating assembly code\n");
	  scanf("%d", &choice);
	  char *s1;
	  char *s2;
	  FILE *tl;
	  FILE *fp;
	  tokenInfo A;
	  int n;
	  switch(choice)
	  {
	    case (1):
	      
	      fp = initLexer(tsf);
	      printf("Token_name  Token_value linenumber\n");
	    do{
		A = getNextToken(fp);
		if((strcmp(A.token,"ID") == 0) || (strcmp(A.token, "FUNID")==0)){
			printf("%s, %s, %d\n", A.token, A.dat.str, A.line);
		}
		else if(strcmp(A.token, "NUM") == 0){
			printf("%s, %d, %d\n", A.token, A.dat.num, A.line);
		}
		else if(strcmp(A.token, "RNUM") == 0){
			printf("%s, %.2f, %d\n", A.token, A.dat.rnum, A.line);
		}
		else{
			printf("%s, %d\n", A.token, A.line);
		}
	     }while((strcmp(A.token,"$") != 0));
	      endLexer(fp);
	      break;
		
	      break;
	   case (2):
	      R = initParser(tsf);					//To parse the input file
	      if(R == NULL) 
		  printf("Input file has not been parsed yet.\n");
	      else
		  printParseTree(R, psrf);
	      break;
	    case (3):
	      R = initParser(tsf);//To parse the input file
	      if(R == NULL) printf("Input file has not been parsed yet.\n");
	      else
	      printParseTree(R, psrf);
	      if(R == NULL) printf("Input file has not been parsed yet.\n");
	      initAST(R);
	      printAST(a);
	      printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Done printing the AST!<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n");
	      break;
	    case (4):
		handleCase4(ST, choice);
		printf("Symbol table population was successful!\n");
		
	      break;
	      case(5):
		handleCase4(ST, choice);
		
	      break;
	    case(6):
	      handleCase4(ST, 6);
	      printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>PERFORMING ASSEMBLY CODE GENERATION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n");
	      genCode(ST, a, "code.asm");
	      break;
	    default:printf("Invalid entry. Please enter a valid choice\n");
	    break;
	  }
	
		//WHY DOES THIS HAVE TO BE PASSED?
	return 0;
}
void handleCase4(symbolTable* ST, int choice)
{
    	R = initParser(tsf);//To parse the input file
	if(R == NULL) printf("Input file has not been parsed yet.\n");
	else
	printParseTree(R, psrf);
	if(R == NULL) printf("Input file has not been parsed yet.\n");
	initAST(R);
	ST = (symbolTable*)calloc(1, sizeof(symbolTable));
	int p;
	for(p = 0; p<50; p++)
	{
	  ST->H[p].pt = NULL;
	}
	int z = 0;
	for(z = 0; z<5; z++)
	{
	  strcpy(ST->inVar[z].name, "$");
	  strcpy(ST->outVar[z].name, "$");;
	}
	ST->parent = NULL;
	ST->funcName = "MAIN";
	//printf("Here name %s\n", ST->funcName);
	ST = createSymbolTable(a, ST);
	if(choice == 4)
	{
		printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>PRINTING THE SYMBOL TABLE<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n");
		printSymbolTable(a, ST);
		printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>FINISHED PRINTING THE SYMBOL TABLE<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n");
	}
	if(choice == 5)
	{
		printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>PERFORMING TYPE AND SEMANTIC CHECKS<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n");	  
		printf("Starting type checking\n");
		int error = initTypeChecker(a, ST);
		if(error != 1)
		printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>TYPE CHECKING COMPLETED SUCCESSFULLY!<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n");
	}
}
/*END OF DRIVER*/